#ifndef IPP_FFI_H
#define IPP_FFI_H

/* Auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct IppChain IppChain;

/**
 * Result of processing a request or response through the plugin chain.
 */
typedef struct IppResult {
  /**
   * JSON object of headers to set: {"key": "value", ...}
   */
  char *mutated_headers_json;
  /**
   * JSON array of header names to remove: ["key1", "key2", ...]
   */
  char *removed_headers_json;
  /**
   * Mutated body bytes (NULL if body unchanged)
   */
  uint8_t *mutated_body;
  /**
   * Length of mutated_body
   */
  uintptr_t mutated_body_len;
  /**
   * Error code: 0=ok, 400=bad_request, 404=not_found, 500=internal
   */
  int32_t error_code;
  /**
   * Error message (NULL if no error)
   */
  char *error_msg;
} IppResult;

/**
 * Initialize the Rust plugin chain.
 *
 * Spawns a tokio runtime, starts kube-rs reconcilers if K8s is available,
 * and builds the full plugin chain.
 *
 * `vertex_config_json` is optional JSON: {"project":"...","location":"...","endpoint":"..."}
 * Pass NULL to skip vertex-openai provider.
 *
 * Returns an opaque handle to the plugin chain, or NULL on failure.
 */
struct IppChain *ipp_init(const char *vertex_config_json);

/**
 * Process a request through the full plugin chain.
 *
 * `headers_json`: JSON object of request headers {"key": "value", ...}
 * `body`: request body bytes
 * `body_len`: length of body
 *
 * Returns a pointer to IppResult. Caller must free with `ipp_free_result`.
 */
struct IppResult *ipp_process_request(struct IppChain *chain,
                                      const char *headers_json,
                                      const uint8_t *body,
                                      uintptr_t body_len);

/**
 * Process a response through the full plugin chain.
 *
 * Uses the CycleState from the last request (maintained internally).
 * Note: In the FFI model, each call creates a fresh CycleState. For proper
 * request-response correlation, the Go bridge must pass provider info via headers.
 */
struct IppResult *ipp_process_response(struct IppChain *chain,
                                       const char *headers_json,
                                       const uint8_t *body,
                                       uintptr_t body_len);

/**
 * Free an IppResult returned by ipp_process_request or ipp_process_response.
 */
void ipp_free_result(struct IppResult *result);

/**
 * Destroy the plugin chain and shut down the tokio runtime.
 */
void ipp_destroy(struct IppChain *chain);

#endif  /* IPP_FFI_H */
